# Generated by Django 5.2.9 on 2026-01-07 00:11

import apps.core.fields
import apps.core.validators
import apps.products.utils
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import model_utils.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('group', models.CharField(choices=[('CAPACITY', 'Capacity'), ('COLOR', 'Color'), ('DEPTH', 'Depth'), ('DIAMETER', 'Diameter'), ('HEIGHT', 'Height'), ('LENGTH', 'Length'), ('MATERIAL', 'Material'), ('QUANTITY', 'Quantity'), ('SIZE', 'Size'), ('THICKNESS', 'Thickness'), ('VOLUME', 'Volume'), ('WEIGHT', 'Weight'), ('WIDTH', 'Width'), ('OTHER', 'Other')], max_length=50, verbose_name='Group')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
                'ordering': ['group', 'name'],
                'indexes': [models.Index(fields=['name'], name='products_at_name_08c5e2_idx'), models.Index(fields=['group'], name='products_at_group_30e276_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_attribute_name')],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('sort_order', apps.core.fields.OrderField(blank=True, for_fields=['attribute'], null=True, verbose_name='Sort order')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.attribute', verbose_name='Attribute')),
            ],
            options={
                'verbose_name': 'Attribute value',
                'verbose_name_plural': 'Attribute values',
                'ordering': ['attribute', 'sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='products/categories/', validators=[apps.core.validators.FileSizeValidator(max_size=5, unit='MB'), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='products_ca_name_693421_idx'), models.Index(fields=['is_active'], name='products_ca_is_acti_a2d000_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_category_name')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, verbose_name='Short description')),
                ('full_description', models.TextField(blank=True, verbose_name='Full description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('attributes', models.ManyToManyField(blank=True, related_name='products', to='products.attribute', verbose_name='Attributes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Stock quantity')),
                ('sort_order', apps.core.fields.OrderField(blank=True, for_fields=['product'], null=True, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product variant',
                'verbose_name_plural': 'Product variants',
                'ordering': ['product', 'sort_order', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(upload_to=apps.products.utils.product_image_upload_to, validators=[apps.core.validators.FileSizeValidator(max_size=5, unit='MB'), django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt text')),
                ('sort_order', apps.core.fields.OrderField(blank=True, for_fields=['product'], null=True, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariant', verbose_name='Product variant')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
                'ordering': ['product', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='products.attribute', verbose_name='Attribute')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.attributevalue', verbose_name='Attribute value')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='Product variant')),
            ],
            options={
                'verbose_name': 'ProductVariant-AttributeValue link',
                'verbose_name_plural': 'ProductVariant-AttributeValue links',
                'ordering': ['product_variant_id', 'attribute_id'],
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='product_variants', through='products.ProductVariantAttributeValue', to='products.attributevalue', verbose_name='Attribute values'),
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('value'), models.F('attribute'), name='unique_attribute_value_per_attribute'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created'], name='products_pr_created_1360ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('category'), name='unique_product_name_per_category'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_51d8ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariantattributevalue',
            constraint=models.UniqueConstraint(fields=('product_variant', 'attribute_value'), name='unique_product_variant_attribute_value_link'),
        ),
        migrations.AddConstraint(
            model_name='productvariantattributevalue',
            constraint=models.UniqueConstraint(fields=('product_variant', 'attribute'), name='unique_product_variant_attribute_link'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_9d6315_idx'),
        ),
    ]
